-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "collectionId" TEXT,
    "price" DOUBLE PRECISION NOT NULL,
    "originalPrice" DOUBLE PRECISION NOT NULL,
    "discountPercent" INTEGER NOT NULL DEFAULT 0,
    "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "reviewCount" INTEGER NOT NULL DEFAULT 0,
    "isNew" BOOLEAN NOT NULL DEFAULT false,
    "isBestSeller" BOOLEAN NOT NULL DEFAULT false,
    "isTrending" BOOLEAN NOT NULL DEFAULT false,
    "image" TEXT NOT NULL,
    "hoverImage" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "finish" TEXT NOT NULL,
    "baseMaterial" TEXT NOT NULL,
    "stoneType" TEXT,
    "warranty" TEXT NOT NULL,
    "inStock" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Product_slug_key" ON "Product"("slug");

-- Insert initial products to satisfy foreign keys for existing cart/wishlist items
INSERT INTO "Product" ("id", "name", "slug", "category", "collectionId", "price", "originalPrice", "discountPercent", "rating", "reviewCount", "isNew", "isBestSeller", "isTrending", "image", "hoverImage", "description", "finish", "baseMaterial", "stoneType", "warranty", "inStock", "createdAt", "updatedAt")
VALUES
    ('prod-br-1', 'Nitya Delicate Crystal Tennis Bracelet', 'nitya-delicate-crystal-tennis-bracelet', 'bracelets', 'the-minimalist', 999, 1899, 47, 4.9, 91, false, true, false, 'https://images.unsplash.com/photo-1590548784585-643d2b9f2925?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?q=80&w=800&auto=format&fit=crop', 'Continuous stream of bezel-set champagne crystals wrapped in a warm gold setting with secure box clasp.', 'Champagne Gold Tone Polish', 'Anti-Allergy Brass Alloy', 'AAA Cubic Zirconia', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-br-2', 'Gaja Heritage Open Cuff Bangle', 'gaja-heritage-open-cuff-bangle', 'bracelets', 'statement', 1499, 2799, 46, 4.9, 67, false, false, true, 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1590548784585-643d2b9f2925?q=80&w=800&auto=format&fit=crop', 'Sculpted elephant head finials gracefully adorned with ruby-toned stone accents and textured antique gold handiwork.', 'Antique City Gold Micron Electroplate', 'Heavy Brass Alloy', 'Hydro Emerald & Ruby Cabochons', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-br-3', 'Subhiksha Temple Lakshmi Kada Pair', 'subhiksha-temple-lakshmi-kada-pair', 'bracelets', 'festive-glow', 1999, 3899, 48, 4.9, 88, false, false, true, 'https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?q=80&w=800&auto=format&fit=crop', 'Pair of screw-open heritage kadas embossed with Goddess Lakshmi figurines, ruby stones, and matte nakshi carving.', 'Temple Antique Gold Polish', 'Brass with Screw Lock Mechanism', 'Synthetic Rubies', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-br-4', 'Aadhya Grace Floral Charm Bracelet', 'aadhya-grace-floral-charm-bracelet', 'bracelets', 'everyday-elegance', 799, 1499, 46, 4.8, 53, true, false, false, 'https://images.unsplash.com/photo-1544441893-675973e31985?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1590548784585-643d2b9f2925?q=80&w=800&auto=format&fit=crop', 'Lightweight gold chain adorned with delicate botanical floral charms and dangling lustrous seed pearls.', '22K Warm Gold Polish', 'Skin-Safe Brass Alloy', 'Cultured Glass Pearls', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-nk-1', 'Royal Kundan Temple Choker Set', 'royal-kundan-temple-choker-set', 'necklaces', 'festive-glow', 1899, 3499, 45, 4.9, 128, false, true, false, 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop', 'A regal city-gold plated choker encrusted with hand-set Kundan stones and delicate pearl drops with matching studs.', '24K Micron Gold Plated', 'High-Grade Brass Alloy', 'Faux Kundan & Cultured Glass Pearls', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-nk-2', 'Kavya Emerald Kundan Rani Haar', 'kavya-emerald-kundan-rani-haar', 'necklaces', 'festive-glow', 2499, 4999, 50, 5, 45, true, true, false, 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop', 'A majestic multi-layered long necklace featuring rich green agate beads, Kundan medallions, and regal tassel adjustments.', '24K Royal Gold Finish', 'Copper Alloy Base', 'Faux Emerald Beads & Uncut Polki', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-nk-3', 'Tarini Modern Sleek Gold Collar Chain', 'tarini-modern-sleek-gold-collar-chain', 'necklaces', 'the-minimalist', 899, 1799, 50, 4.8, 62, false, false, false, 'https://images.unsplash.com/photo-1599643477877-530eb83abc8e?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1611085583191-a3b181a88401?q=80&w=800&auto=format&fit=crop', 'A smooth fluid snake chain collar that catches light with every subtle movement. Ultra-modern and refined.', '18K High-Shine Gold Plating', 'Anti-Tarnish Stainless Steel', NULL, '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-nk-4', 'Ira Statement Heritage Hasli Choker', 'ira-statement-heritage-hasli-choker', 'necklaces', 'statement', 1699, 3199, 47, 4.9, 74, false, false, true, 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop', 'Traditional torque collar Hasli crafted with intricate nakshi engraving and champagne crystal drop accents.', 'Antique Matte Gold Polish', 'Solid Brass Alloy', 'Hydro Crystals', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-er-1', 'Mayura Heritage Chandbali Jhumkas', 'mayura-heritage-chandbali-jhumkas', 'earrings', 'statement', 1249, 2299, 45, 4.8, 94, false, false, true, 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop', 'Intricately carved peacock motifs accented with antique gold finish and clusters of tiny ghungroo beads.', 'Antique City Gold Polish', 'Copper-Brass Alloy', 'Ruby-Red Hydro Crystals', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-er-2', 'Aadhya Delicate Floral Drop Studs', 'aadhya-delicate-floral-drop-studs', 'earrings', 'everyday-elegance', 649, 1299, 50, 4.8, 110, false, false, false, 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop', 'Charming botanical petaled studs with a singular dangling drop pearl. Lightweight and hypoallergenic.', '22K Warm Gold Tone', 'Hypoallergenic Brass', 'Freshwater Imitation Pearl', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-er-3', 'Ananya Kundan Passa & Jhumka Set', 'ananya-kundan-passa-jhumka-set', 'earrings', 'festive-glow', 1699, 3299, 48, 4.9, 39, true, false, false, 'https://images.unsplash.com/photo-1635767798638-3e25273a8236?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1630019852942-f89202989a59?q=80&w=800&auto=format&fit=crop', 'Exquisite bridal side pasa paired with cascading Jhumkas featuring delicate seed pearls and emerald drops.', '24K Gold Plated Heritage Finish', 'Jewellery-Grade Copper Brass', 'Polki & Agate Beads', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-er-4', 'Tara Everyday Twisted Gold Hoops', 'tara-everyday-twisted-gold-hoops', 'earrings', 'the-minimalist', 549, 999, 45, 4.9, 142, false, true, false, 'https://images.unsplash.com/photo-1596944924616-7b38e7cfac36?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop', 'Comfortable lightweight twisted cable hoops crafted in gleaming 18K city gold finish for all-day elegance.', '18K Glossy Gold Dipped', 'Anti-Tarnish Alloy', NULL, '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-er-5', 'Aarohi Pearl Drop Sui Dhaga Earrings', 'aarohi-pearl-drop-sui-dhaga-earrings', 'earrings', 'everyday-elegance', 699, 1399, 50, 4.7, 58, false, false, false, 'https://images.unsplash.com/photo-1589128777073-263566ae5e4d?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1629224316810-9d8805b95e76?q=80&w=800&auto=format&fit=crop', 'Slender threader earrings featuring flowing gold link chains tipped with luminous teardrop pearls.', '24K Micron Gold Plated', 'Hypoallergenic Brass', 'Cultured Glass Pearls', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-rg-1', 'Victorian Polki Solitaire Adjustable Ring', 'victorian-polki-solitaire-adjustable-ring', 'rings', 'the-minimalist', 599, 1199, 50, 4.7, 82, true, false, false, 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop', 'A dazzling oval uncut Polki stone set in an ornate vintage filigree crown with an adjustable band.', 'Champagne Gold Plating', 'Jewellery-Grade Brass', 'Uncut Glass Polki', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-rg-2', 'Meera Filigree Gold Stackable Ring Set', 'meera-filigree-gold-stackable-ring-set', 'rings', 'everyday-elegance', 699, 1399, 50, 4.6, 78, false, false, false, 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop', 'Set of 3 distinct thin gold bands featuring twisted ropes, geometric micro-studs, and a crystal solitaire.', '18K Yellow Gold Dip', 'Brass Alloy', 'Swiss Zirconia', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-rg-3', 'Vanya Minimalist Geometric Band', 'vanya-minimalist-geometric-band', 'rings', 'the-minimalist', 499, 999, 50, 4.8, 115, false, true, false, 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?q=80&w=800&auto=format&fit=crop', 'Clean beveled facet band designed with modern symmetry and reflective high-polish mirror finish.', '18K Mirror Gold Polish', 'Stainless Steel', NULL, '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-rg-4', 'Padmavati Lotus Kundan Statement Ring', 'padmavati-lotus-kundan-statement-ring', 'rings', 'statement', 899, 1699, 47, 4.9, 64, false, false, true, 'https://images.unsplash.com/photo-1608042314453-ae338d80c427?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop', 'Artisanal blooming lotus silhouette studded with uncut white Polki and ruby glass enamel center.', '24K Antique Temple Gold', 'Brass Alloy', 'Kundan & Synthetic Ruby', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-ch-1', 'Meher Classic Rope Gold Chain', 'meher-classic-rope-gold-chain', 'chains', 'everyday-elegance', 849, 1599, 47, 4.9, 134, false, true, false, 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=800&auto=format&fit=crop', 'Densely woven twisted rope chain offering shimmering multi-faceted sparkle, perfect alone or with pendants.', '24K Micron Gold Plated', 'Jewellery-Grade Brass', NULL, '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-ch-2', 'Divya Figaro Link City Gold Chain', 'divya-figaro-link-city-gold-chain', 'chains', 'the-minimalist', 949, 1799, 47, 4.8, 89, false, false, false, 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?q=80&w=800&auto=format&fit=crop', 'Timeless Italian-inspired 3+1 Figaro link pattern finished in rich city gold tone with sturdy lobster clasp.', '18K Yellow Gold Dip', 'Stainless Steel', NULL, '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-ch-3', 'Samaira Sleek Herringbone Chain', 'samaira-sleek-herringbone-chain', 'chains', 'statement', 1099, 2199, 50, 4.9, 76, false, false, true, 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1598560917505-59a3ad559071?q=80&w=800&auto=format&fit=crop', 'Silky smooth flat herringbone chain that sits flush against the collarbone with liquid gold radiance.', '24K Micron Gold Electroplate', 'Brass Alloy', NULL, '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-pd-1', 'Avira Floral Polki Pendant with Chain', 'avira-floral-polki-pendant-with-chain', 'pendants', 'everyday-elegance', 749, 1499, 50, 4.9, 112, false, true, false, 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop', 'Artisanal flower bloom pendant centered with radiant glass Polki crystal and suspended on an 18-inch gold chain.', '22K Warm Gold Tone', 'Hypoallergenic Brass', 'Uncut Glass Polki', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-pd-2', 'Minimalist Layered Crescent Pendant Chain', 'minimalist-layered-crescent-pendant-chain', 'pendants', 'the-minimalist', 799, 1499, 46, 4.8, 156, false, false, false, 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop', 'Double-strand delicate gold chain with a brushed crescent moon token designed for modern daily wear.', '18K Matte Gold Polish', 'Anti-Tarnish Stainless Steel', 'Cubic Zirconia Accent', '1 Year Anti-Tarnish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-pd-3', 'Gayatri Solitaire Teardrop Pendant', 'gayatri-solitaire-teardrop-pendant', 'pendants', 'the-minimalist', 699, 1399, 50, 4.7, 48, true, false, false, 'https://images.unsplash.com/photo-1629224316810-9d8805b95e76?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop', 'Pear-cut faceted sparkling crystal framed in a three-prong bezel gold cup with fine gold link chain.', 'Champagne Gold Tone', 'Brass Alloy', 'AAA Cubic Zirconia', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('prod-pd-4', 'Navya Antique Temple Coin Pendant', 'navya-antique-temple-coin-pendant', 'pendants', 'festive-glow', 899, 1699, 47, 4.9, 69, false, false, true, 'https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?q=80&w=800&auto=format&fit=crop', 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop', 'Heritage Kasu coin medallion embossed with auspicious motifs and framed in delicate beaded granulation.', 'Antique Temple Gold Polish', 'Copper-Brass Alloy', 'Synthetic Ruby Accents', '6 Months Polish Guarantee', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

-- AddForeignKey
ALTER TABLE "CartItem" ADD CONSTRAINT "CartItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WishlistItem" ADD CONSTRAINT "WishlistItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE CASCADE ON UPDATE CASCADE;
